### PR TITLE
Randomize activities and stories

### PR DESCRIPTION
**Pull request by andycarnahan**
- get activities and stories in random order for the archive pages
- intersperse "add bordr story" items (in the same style as the actual bordr stories) among the stories on the bordr stories archive

### CODE REVIEW

**Comment by jcdk** [comment]
Issue I see with the randomization is that activities and stories get duplicated with the infinite scroll.  I'm not sure how to avoid duplicated posts.

**Comment by andycarnahan** [comment]
Shoot, infinite scroll is buggy on my local machine still, so I didn't realize. Surely this is a problem that other people have had. I'll figure it out.

**Comment by andycarnahan** [comment]
This should fix it, but infinite scroll is behaving badly on my local machine, so I'm not really sure until we try it on dev.

The "seed" for the (psuedo)random order stays the same for the session, which should infinite scroll (and other pagination) load the next posts without dupes.

I realize it has a (possibly unwanted?) side effect, which is that the stories won't shuffle if you reload the page; the order will be the same until the session ends. If we really don't want this, we could maybe figure out a way to reset the seed, but no ideas immediately come to mind.

**Comment by jcdk** [comment]
Glad you could figure it out and I rather like the idea that the order of activities and stories are maintained through the session.  Watching recordings of user behavior, people appear to expect consistency in the order of activities and stories during a session.  I believe maintaining the same order until the session ends is a feature.

**Comment by andycarnahan** [comment]
Great! It's nice when side effects are beneficial every once in a while. :)

**Comment by jcdk** [comment]
I have the branch up on dev right now.  Seems like the first two rows of results gets repeated with infinite scroll results, but those are the only results that get duplicated.  Any thought what may be doing that?

**Comment by andycarnahan** [comment]
Dang, I don't have any theories right away... I'll look at it again.

**Comment by jcdk** [comment]
Just talked to @haraldssonfoto and we think that unless you see some easy fix for this, we'll just proceed with pulling these commits into master without the randomization effect on activities.

**Pull request merged**
