### PR TITLE
Simple video home

### PR DESCRIPTION
**Pull request by jcdk**

### CODE REVIEW

**Comment by andycarnahan** [comment]
I'm having trouble figuring out this footer problem... The footer shows on my local but not on the development server. It's there in the page source even on the development server (so it's rendering the footer.php), but it's not visible on the page.

**Comment by andycarnahan** [comment]
Ah, it's hidden because of something with infinite scroll. That  doesn't explain why it's hidden on development and not on local, but there it is.

image

**Comment by andycarnahan** [comment]
I'm afraid I'll mess up infinite scroll somewhere else if I mess with it, so I'm going to hard code the footer into home for now (with different class/id so it doesn't get disappeared by infinite scroll), so we can roll out.

**Comment by jcdk** [comment]
Yeah, I'm not sure that it is necessary for the footer to be hidden on archive pages that use infinite scroll. Does it look weird if it is always showing?

Not sure where WP is setting the control to hide the footer, so I'm taking your idea and changed the main footer ID to "footer-static".

**Pull request merged**
