### PR TITLE
Pretty masonry stories

### PR DESCRIPTION
**Pull request by jcdk**

### CODE REVIEW

**Comment by andycarnahan** [comment]
I probably should have squashed commits.

**Comment by jcdk** [comment]
All good.  Would it be a quick fix to show the updated stories format when the user is logged-out?

**Comment by andycarnahan** [comment]
I thought it does show when the user is logged out, or maybe I don't understand the question?

Unrelated to that, there's a left-pointing arrow at the bottom to go to page 2; it should probably be switched out for a right-pointing arrow or something.

**Comment by jcdk** [comment]
Yeah, for some reason it isn't showing when I log out of the site. It returns to the previous format.

Agree on the arrow.  Probably would make a lot of sense to use the GGC stylized arrow.

**Comment by andycarnahan** [comment]
Oh, weird. I'll check it out. I developed the whole thing while logged out, so I'm not sure why that's happening. Good call on the stylized arrow.

**Comment by andycarnahan** [comment]
image

I can't replicate that (see above where I'm logged out)... maybe it's cached on your machine or something?

**Comment by jcdk** [comment]
Very interesting!  @haraldssonfoto says he's seeing the same thing I am.  You know what, it probably is cached with WP Cache.  I'll check and empty that now.  Thanks for checking!

**Comment by andycarnahan** [comment]
Cool, let me know if that doesn't fix it and I'll try to figure out what's going on!

**Comment by jcdk** [comment]
That worked!  Okay, I'm going to merge the pull request.

**Pull request merged**
